import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "FixiByte - CMMS Software & AI Predictive Maintenance Platform | Sustainabyte",
  description: "Eliminate unplanned downtime with FixiByte CMMS software. AI-powered equipment fault detection, automated work orders, vibration monitoring, and asset lifecycle tracking.",
  keywords: [
    "CMMS software",
    "predictive maintenance software",
    "equipment health monitoring",
    "FixiByte",
    "FixByte",
    "predictive maintenance",
    "Compressor health monitoring",
    "Compressor diagnostics",
    "Compressor alarm monitoring",
    "Compressor trend analysis",
    "Compressor fault analysis",
    "Compressor predictive maintenance",
    "Compressor digital twin",
    "Compressor KPI",
    "Compressor health index",
    "Compressor asset management",
    "Compressor fault detection",
    "Compressor monitoring software",
    "Compressor health analytics",
    "Compressor lifecycle analysis",
    "Air compressor maintenance",
    "Air compressor savings",
    "Air compressor AI monitoring",
    "Air compressor diagnostics",
    "Air compressor asset monitoring",
    "Air compressor predictive maintenance",
    "Air compressor performance dashboard",
    "Air compressor monitoring solution",
    "Boiler maintenance",
    "Boiler diagnostics",
    "Boiler fault analysis",
    "Boiler trend monitoring",
    "Boiler predictive maintenance",
    "Boiler digital twin",
    "Boiler health monitoring",
    "Boiler health index",
    "Boiler alarm management",
    "Boiler lifecycle analysis",
    "Boiler reliability analytics",
    "Boiler asset management",
    "Boiler performance monitoring",
    "Steam health monitoring",
    "Steam maintenance planning",
    "Cooling tower maintenance",
    "Cooling tower health monitoring",
    "Pump health monitoring",
    "Pump vibration monitoring",
    "Pump predictive maintenance",
    "Pump diagnostics",
    "Motor health monitoring",
    "Motor diagnostics",
    "Motor predictive maintenance",
    "Motor health index",
    "Motor asset management",
    "Capacitor health monitoring",
    "Transformer health monitoring",
    "Transformer diagnostics",
    "Asset health monitoring",
    "Equipment health monitoring",
    "Utility asset health index",
    "Asset condition monitoring",
    "Equipment condition assessment",
    "Equipment reliability monitoring",
    "Asset degradation monitoring",
    "Equipment lifecycle monitoring",
    "Utility asset diagnostics",
    "Equipment health dashboard",
    "Utility alarm management",
    "Utility alerts",
    "SMS alerts",
    "WhatsApp alerts",
    "Email alerts",
    "Fault notification",
    "Critical alarm monitoring",
    "Utility event monitoring",
    "Utility warning alerts",
    "Automated notifications",
    "Escalation alerts",
    "Downtime alerts",
    "Utility failure alerts",
    "Equipment fault alerts",
    "Utility threshold alerts",
    "Predictive maintenance",
    "AI predictive maintenance",
    "Equipment failure prediction",
    "Asset reliability analytics",
    "Maintenance forecasting",
    "Remaining useful life",
    "Asset health score",
    "Equipment risk assessment",
    "Failure mode analysis",
    "Condition-based maintenance",
    "Predictive diagnostics",
    "Equipment anomaly detection",
    "Machine learning maintenance",
    "Maintenance intelligence",
    "Smart maintenance platform",
    "Chiller fault detection",
    "Chiller alarm management",
    "Compressor fault detection",
    "Compressor alarm system",
    "Compressor health score",
    "Boiler health index",
    "Pump condition monitoring",
    "Pump alarm management",
    "Pump health score",
    "Pump reliability monitoring",
    "Cooling tower alarm system",
    "Motor vibration monitoring",
    "Motor fault detection"
  ],
  openGraph: {
    title: "FixByte - Predictive Maintenance",
    description: "AI-powered equipment health monitoring and failure prediction",
    url: "https://sustainabyte.ai/technology/fixbyte",
    images: [
      {
        url: "/opengraph-image.png",
        width: 1200,
        height: 630,
        alt: "FixByte - Sustainabyte",
      },
    ],
  },
  alternates: {
    canonical: "https://sustainabyte.ai/technology/fixbyte",
  },
};

export default function FixByteLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return children;
}
