import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Energy Audit Services in Chennai | Industrial & Commercial | BEE Certified | Sustainabyte",
  description:
    "Leading Energy Audit Company in Chennai. BEE certified industrial & commercial energy audits, ASHRAE Level 1-3 audits, ISO 50001 & ISO 50002 consulting. Serving Chennai, Tamil Nadu & pan-India. 10-30% verified energy savings.",
  keywords: [
    // 🔑 Chennai primary audit keywords
    "Energy Audit Company in Chennai",
    "Energy Audit Services in Chennai",
    "Industrial Energy Audit in Chennai",
    "Commercial Energy Audit in Chennai",
    "Energy Audit Tamil Nadu",
    "Energy Consultant in Chennai",
    "Energy Consulting Company in Chennai",
    "Energy Conservation Services in Chennai",
    "Factory Energy Audit Chennai",
    "Manufacturing Energy Audit Chennai",
    "Hospital Energy Audit Chennai",
    "Hotel Energy Audit Chennai",
    "IT Park Energy Audit Chennai",
    "Commercial Building Energy Audit Chennai",
    "HVAC Energy Audit Chennai",
    "Chiller Plant Audit Chennai",
    "Electrical Energy Audit Chennai",
    "Building Energy Audit Chennai",
    // 🔧 Service type keywords
    "Energy audit",
    "Electrical energy audit",
    "HVAC energy audit",
    "Industrial energy audit",
    "Commercial energy audit",
    "Building energy audit",
    "Energy performance assessment",
    "Energy consumption analysis",
    "Energy saving assessment",
    "Energy efficiency assessment",
    "Energy conservation study",
    "ISO 50001 consulting",
    "ISO 50002 energy audit",
    // ✅ Existing service keywords
    "energy audit services",
    "ISO 50001 consulting",
    "industrial energy efficiency",
    "BEE energy audit",
    "ASHRAE energy audit",
    "ISO 50002 audit",
    "energy audit India",
    "energy audit UAE",
    "energy audit Dubai",
    "energy audit Saudi Arabia",
    "energy audit KSA",
    "energy audit Singapore",
    "energy audit Malaysia",
    "energy audit Qatar",
    "energy audit Bahrain",
    "energy audit Kuwait",
    "energy audit Oman",
    "energy audit Indonesia",
    "energy audit Philippines",
    "energy audit Thailand",
    "energy audit Vietnam",
    "energy audit UK",
    "energy audit USA",
    "energy audit Australia",
    "energy audit Canada",
    "energy audit Germany",
    "energy audit Japan",
    "energy audit South Korea",
    "energy audit Middle East",
    "energy audit Southeast Asia",
    "energy audit Asia Pacific",
    "energy audit GCC countries",
    "energy audit MENA region",
    "international energy audit services",
    "global energy audit company",
    "preliminary energy audit",
    "detailed energy audit",
    "investment grade energy audit",
    "industrial energy audit",
    "commercial building energy audit",
    "BEE energy audit",
    "ISO 50001 energy audit",
    "energy audit consultants",
    "energy audit report",
    "Compressor audit",
    "Air leak audit",
    "Acoustic imaging",
    "Air leak detection",
    "Compressed air audit",
    "Air system audit",
    "Boiler audit",
    "Steam audit",
    "Steam trap audit",
    "Steam leak survey",
    "AHU audit",
    "Ventilation audit",
    "HVAC audit",
    "Pump Audit",
    "Pump audit",
    "Cooling tower audit",
    "Motor audit",
    "Power quality audit",
    "Capacitor bank audit",
    "Oven audit",
    "Paint shop energy audit",
    "Furnace audit",
    "Detailed energy audit",
    "Preliminary energy audit",
    "Walk through audit",
    "Utility audit",
    "Electrical audit",
    "Thermal audit",
    "Energy conservation measures",
    "ECM identification",
    "Energy savings calculation",
    "ROI calculation",
    "Payback calculation",
    "M&V study",
    "Baseline development",
    "SEC analysis",
    "Benchmarking study",
    "Utility mapping",
    "Heat balance",
    "Sankey diagram",
    "Energy flow diagram",
    "Utility optimization",
    "Cost reduction study",
    "Energy management plan",
    "Chiller plant audit"
  ],
  openGraph: {
    title: "Energy Audit Services | BEE Certified | Sustainabyte",
    description: "AI-powered energy audits for industries & buildings across 20+ countries. 10-30% energy savings identified.",
    url: "https://sustainabyte.ai/energy/energy-audit",
    type: "website",
    images: [
      {
        url: "https://sustainabyte.ai/opengraph-image.png",
        width: 1200,
        height: 630,
        alt: "Energy Audit Services - BEE Certified",
      },
    ],
  },
  alternates: {
    canonical: "https://sustainabyte.ai/energy/energy-audit",
    languages: {
      "en-IN": "https://sustainabyte.ai/energy/energy-audit",
      "en-AE": "https://sustainabyte.ai/energy/energy-audit",
      "en-SA": "https://sustainabyte.ai/energy/energy-audit",
      "en-SG": "https://sustainabyte.ai/energy/energy-audit",
      "en-MY": "https://sustainabyte.ai/energy/energy-audit",
      "en-GB": "https://sustainabyte.ai/energy/energy-audit",
      "en-US": "https://sustainabyte.ai/energy/energy-audit",
      "en-AU": "https://sustainabyte.ai/energy/energy-audit",
    },
  },
};

export default function EnergyAuditLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return children;
}
