import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Chiller Plant Manager | Sustainabyte",
  description: "Optimize chiller plant performance with real-time monitoring, predictive maintenance, and autonomous controls powered by AI and IoT.",
  keywords: [
    "Chiller Plant Manager",
    "chiller optimization",
    "plant management",
    "Chiller COP",
    "Chiller efficiency",
    "Chiller kW/TR",
    "Chiller energy saving",
    "Chiller audit",
    "Chiller performance",
    "Chiller loading",
    "Chiller unloading",
    "Chiller sequencing",
    "Chiller staging",
    "Chiller runtime",
    "Chiller health monitoring",
    "Chiller power consumption",
    "Chiller demand analysis",
    "Chiller condenser temperature",
    "Chiller evaporator temperature",
    "Chilled water flow",
    "Chilled water return temperature",
    "Chilled water supply temperature",
    "Chiller delta T",
    "Chiller approach",
    "Chiller tube cleaning",
    "Chiller fouling",
    "Chiller maintenance",
    "Chiller diagnostics",
    "Chiller fault detection",
    "Chiller analytics",
    "Chiller dashboard",
    "Chiller report",
    "Chiller benchmarking",
    "Chiller energy baseline",
    "Chiller operating cost",
    "Chiller energy consumption",
    "Screw chiller",
    "Centrifugal chiller",
    "Air cooled chiller",
    "Water cooled chiller",
    "Magnetic bearing chiller",
    "Chiller retrofit",
    "Chiller replacement",
    "Chiller setpoint",
    "Chiller control logic",
    "Chiller PLC integration",
    "Chiller automation",
    "Chiller plant monitoring",
    "Chiller optimization study",
    "Chiller savings calculation",
    "Chiller efficiency improvement",
    "Chiller load balancing",
    "Chiller pump optimization",
    "Chiller condenser pressure",
    "Chiller evaporator pressure",
    "Chiller capacity utilization",
    "Chiller trend analysis",
    "Chiller performance degradation",
    "Chiller digital twin",
    "Chiller KPI",
    "Chiller alarm",
    "Chiller operation review",
    "Chiller data analytics",
    "Chiller monitoring system",
    "Chiller maintenance planning",
    "Chiller fault analysis",
    "Chiller energy management",
    "Chiller commissioning",
    "Chiller recommissioning",
    "Chiller seasonal efficiency",
    "Chiller IPLV",
    "Chiller NPLV",
    "Chiller efficiency curve",
    "Chiller optimization dashboard",
    "Chiller AI monitoring",
    "Chiller predictive maintenance",
    "Chiller health index",
    "Chiller energy report",
    "Chiller plant audit",
    "Chiller plant efficiency",
    "Chiller energy reduction",
    "Chiller fault diagnosis",
    "Chiller optimization software",
    "Chiller monitoring dashboard",
    "Chiller operating strategy",
    "Chiller load profile",
    "Chiller energy benchmarking",
    "Chiller asset management",
    "Chiller plant analytics",
    "Chiller savings tracker",
    "Chiller operating hours",
    "Chiller demand control",
    "Chiller lifecycle analysis",
    "Chiller energy intelligence",
    "Chiller operating efficiency",
    "Chiller utility optimization",
    "Chiller energy trends",
    "Chiller digital monitoring",
    "Chiller plant management",
    "Chiller efficiency dashboard",
    "Chiller optimization recommendations",
    "Chiller performance report",
    "Chiller monitoring",
    "Chiller automation",
    "Chiller performance monitoring",
    "Chiller health monitoring",
    "Chiller COP monitoring",
    "Chiller optimization control",
    "Chiller sequencing automation",
    "Chiller staging automation",
    "Chiller remote monitoring",
    "Chiller plant automation",
    "Chiller KPI dashboard",
    "Chiller alarm management"
  ],
  openGraph: {
    title: "Chiller Plant Manager",
    description: "AI-powered chiller plant optimization and monitoring",
    url: "https://sustainabyte.ai/technology/chiller-plant-manager",
    images: [
      {
        url: "/opengraph-image.png",
        width: 1200,
        height: 630,
        alt: "Chiller Plant Manager - Sustainabyte",
      },
    ],
  },
  alternates: {
    canonical: "https://sustainabyte.ai/technology/chiller-plant-manager",
  },
};

export default function ChillerPlantLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return children;
}
