import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "OptiByte - AI Energy Intelligence Platform | Sustainabyte",
  description: "OptiByte consolidates energy data, runs predictive models, and orchestrates autonomous optimization across your facility portfolio. The central AI brain.",
  keywords: [
    "OptiByte",
    "energy intelligence platform",
    "AI energy management",
    "OptiByte dashboard",
    "OptiByte reports",
    "OptiByte alarms",
    "OptiByte alerts",
    "OptiByte monitoring",
    "OptiByte analytics",
    "OptiByte KPI",
    "OptiByte energy report",
    "OptiByte utility dashboard",
    "OptiByte AI recommendations",
    "OptiByte anomaly detection",
    "OptiByte benchmarking",
    "OptiByte trend analysis",
    "OptiByte savings tracker",
    "OptiByte energy intelligence",
    "OptiByte asset monitoring",
    "OptiByte maintenance analytics",
    "OptiByte plant dashboard",
    "OptiByte multi-site dashboard",
    "OptiByte management dashboard",
    "Compressor efficiency",
    "Compressor specific power",
    "Compressor power consumption",
    "Compressor load analysis",
    "Compressor unloading losses",
    "Compressor pressure optimization",
    "Compressor sequencing",
    "Compressor control logic",
    "Compressor VFD",
    "Compressor energy saving",
    "Compressor energy baseline",
    "Compressor capacity utilization",
    "Compressor operating cost",
    "Screw compressor",
    "Centrifugal compressor",
    "Oil free compressor",
    "Oil injected compressor",
    "Variable speed compressor",
    "Fixed speed compressor",
    "Compressor air flow",
    "Compressor pressure drop",
    "Compressor discharge pressure",
    "Compressor suction pressure",
    "Compressor heat recovery",
    "Compressor network analysis",
    "Compressor optimization study",
    "Compressor plant monitoring",
    "Compressor performance degradation",
    "Compressor operating strategy",
    "Compressor demand control",
    "Compressor utilization analysis",
    "Compressor cost optimization",
    "Air network balancing",
    "Air system optimization",
    "Air leak quantification",
    "Air consumption mapping",
    "Air compressor energy monitoring",
    "Boiler efficiency",
    "Boiler combustion efficiency",
    "Flue gas analysis",
    "Boiler fuel consumption",
    "Steam generation",
    "Condensate recovery",
    "Steam balance",
    "Boiler blowdown",
    "Boiler optimization",
    "Boiler monitoring",
    "Boiler efficiency improvement",
    "Boiler energy saving",
    "Excess air optimization",
    "Oxygen monitoring",
    "Stack temperature analysis",
    "Fuel savings calculation",
    "Boiler load analysis",
    "Boiler operating cost",
    "Steam pressure optimization",
    "Steam distribution",
    "Steam dryness fraction",
    "Steam utilization efficiency",
    "Steam generation cost",
    "Steam loss analysis",
    "Steam demand profile",
    "Steam header pressure",
    "Steam flow measurement",
    "Steam optimization",
    "Steam savings calculation",
    "PNG boiler",
    "LPG boiler",
    "Biomass boiler",
    "FO boiler",
    "Diesel boiler",
    "Electric boiler",
    "Thermal oil heater",
    "Economizer performance",
    "Air preheater efficiency",
    "Boiler feed water optimization",
    "Boiler water treatment",
    "Boiler fuel tracking",
    "Boiler heat balance",
    "Thermal efficiency calculation",
    "Combustion optimization",
    "Fuel cost optimization",
    "Waste heat recovery",
    "Pump efficiency",
    "Pump optimization",
    "Pump power consumption",
    "Pump flow analysis",
    "Pump head analysis",
    "Pump energy saving",
    "Pump operating point",
    "Pump BEP",
    "Pump efficiency curve",
    "Pump system curve",
    "Pump load analysis",
    "Chilled water pump",
    "Condenser water pump",
    "Cooling tower pump",
    "Process water pump",
    "Fire water pump",
    "Transfer pump",
    "Booster pump",
    "Utility water pump",
    "Pump flow measurement",
    "Pump VFD optimization",
    "Cooling tower optimization",
    "Cooling tower efficiency",
    "Cooling tower approach",
    "Cooling tower range",
    "Cooling tower fan optimization",
    "Cooling tower water balance",
    "Cooling tower energy consumption",
    "Cooling tower drift loss",
    "Cooling tower blowdown",
    "Motor efficiency",
    "Motor optimization",
    "Motor loading",
    "Motor current analysis",
    "Motor power factor",
    "Motor power consumption",
    "IE2 motor",
    "IE3 motor",
    "IE4 motor",
    "Premium efficiency motor",
    "Motor replacement study",
    "Motor right sizing",
    "Motor energy saving",
    "VFD audit",
    "VFD optimization",
    "VFD energy saving",
    "VFD load analysis",
    "VFD efficiency improvement",
    "Power Quality",
    "Harmonic analysis",
    "THD analysis",
    "Voltage imbalance",
    "Current imbalance",
    "Harmonic mitigation",
    "Harmonic filter",
    "Active harmonic filter",
    "Passive harmonic filter",
    "Maximum demand",
    "Peak demand reduction",
    "Demand control",
    "Demand optimization",
    "Contract demand",
    "Demand penalty",
    "Demand forecasting",
    "Demand management system",
    "Transformer efficiency",
    "Transformer loading",
    "Transformer losses",
    "Transformer energy saving",
    "Power factor correction",
    "APFC panel",
    "Reactive power analysis",
    "PF improvement",
    "PF penalty reduction",
    "Oven efficiency",
    "Oven optimization",
    "Oven fuel consumption",
    "Oven PNG consumption",
    "Oven insulation study",
    "Oven heat loss",
    "Oven heat balance",
    "Oven exhaust losses",
    "Oven energy saving",
    "Paint oven optimization",
    "Paint curing oven",
    "Powder coating oven",
    "Furnace efficiency",
    "Furnace optimization",
    "Furnace fuel consumption",
    "Furnace combustion efficiency",
    "Furnace heat balance",
    "Furnace exhaust loss",
    "Furnace insulation improvement",
    "Utility automation",
    "Smart utility control",
    "Automated utility management",
    "Utility control system",
    "Utility automation dashboard",
    "Intelligent utility control",
    "Utility optimization automation",
    "Automatic utility operation",
    "Utility automation platform",
    "Automated utility scheduling",
    "Control logic optimization",
    "Equipment automation logic",
    "Process control automation",
    "Automatic start stop control",
    "Load-based automation",
    "Demand-based automation",
    "Setpoint automation",
    "Automatic sequencing",
    "Equipment scheduling",
    "Smart control strategy",
    "Compressor automation",
    "Compressor sequencing automation",
    "Compressor load sharing",
    "Compressor pressure control",
    "Compressor runtime monitoring",
    "Compressor optimization control",
    "Compressor performance analytics",
    "Boiler automation",
    "Boiler combustion monitoring",
    "Boiler oxygen control",
    "Boiler fuel monitoring",
    "Boiler AI optimization",
    "Boiler combustion automation",
    "Boiler burner control",
    "Boiler efficiency analytics",
    "Pump automation",
    "Pump runtime monitoring",
    "Pump optimization control",
    "Pump pressure monitoring",
    "Pump flow monitoring",
    "Cooling tower automation",
    "Cooling tower fan automation",
    "Cooling tower water monitoring",
    "Cooling tower optimization control",
    "Cooling tower approach monitoring",
    "Cooling tower range monitoring",
    "VFD automation",
    "VFD analytics",
    "VFD health monitoring",
    "VFD fault analysis",
    "Automatic energy reporting",
    "Automated KPI generation",
    "Energy analytics automation",
    "Utility optimization engine",
    "AI energy management",
    "Automated savings tracking",
    "Automated performance benchmarking",
    "Energy anomaly detection",
    "Smart energy control",
    "Utility digital twin",
    "Equipment digital twin",
    "Chiller digital twin",
    "Boiler digital twin",
    "Compressor digital twin",
    "Asset digital twin",
    "AI utility analytics",
    "AI fault detection",
    "AI energy optimization",
    "AI asset monitoring",
    "Machine learning analytics",
    "Utility intelligence engine",
    "Operational intelligence",
    "Autonomous utility optimization",
    "Smart factory utility monitoring"
  ],
  openGraph: {
    title: "OptiByte - AI Energy Platform",
    description: "Consolidate energy data and run autonomous optimization across your portfolio",
    url: "https://sustainabyte.ai/technology/optibyte",
    images: [
      {
        url: "/opengraph-image.png",
        width: 1200,
        height: 630,
        alt: "OptiByte - Sustainabyte",
      },
    ],
  },
  alternates: {
    canonical: "https://sustainabyte.ai/technology/optibyte",
  },
};

export default function OptiByteLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return children;
}
