import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Energy Audit & Energy Management Services in Chennai | Sustainabyte",
  description: "Sustainabyte provides Energy Audit, Energy Management, and Energy Efficiency services in Chennai & Tamil Nadu. BEE certified auditors, ISO 50001 consulting, industrial & commercial energy audits.",
  keywords: [
    // 🔑 Main Chennai company keywords
    "Energy Audit Company in Chennai",
    "Energy Audit Services in Chennai",
    "Energy Service Company in Chennai",
    "Energy Management Company in Chennai",
    "Energy Efficiency Company in Chennai",
    "Energy Consulting Company in Chennai",
    "Energy Consultant in Chennai",
    "Industrial Energy Audit in Chennai",
    "Commercial Energy Audit in Chennai",
    "Energy Conservation Services in Chennai",
    "Energy Optimization Company in Chennai",
    "Energy Management Services in Chennai",
    // 🔧 Service type keywords
    "Energy audit",
    "Electrical energy audit",
    "HVAC energy audit",
    "Industrial energy audit",
    "Commercial energy audit",
    "Building energy audit",
    "Energy performance assessment",
    "Energy consumption analysis",
    "Energy saving assessment",
    "Energy efficiency assessment",
    "Energy conservation study",
    "Energy monitoring",
    "Energy optimization",
    "Chiller plant optimization",
    "HVAC optimization",
    "ISO 50001 consulting",
    "ISO 50002 energy audit",
    // 📍 Chennai location keywords
    "Energy Audit Chennai",
    "Energy Audit Company Chennai",
    "Energy Consultant Chennai",
    "Energy Management Chennai",
    "Energy Efficiency Chennai",
    "Energy Services Chennai",
    "Energy Optimization Chennai",
    "Industrial Energy Consultant Chennai",
    "Energy Audit Tamil Nadu",
    "Energy Management Tamil Nadu",
    "Energy Efficiency Services Tamil Nadu",
    // 🏭 Industry verticals Chennai
    "Factory Energy Audit Chennai",
    "Manufacturing Energy Audit Chennai",
    "Hospital Energy Audit Chennai",
    "Hotel Energy Audit Chennai",
    "IT Park Energy Management Chennai",
    "Commercial Building Energy Audit Chennai",
    "Industrial Energy Efficiency Chennai",
    "Factory Energy Management Chennai",
    "HVAC Energy Optimization Chennai",
    "Chiller Optimization Chennai",
    // ✅ CORE PRODUCT
    "energy management software",
    "energy efficiency consulting",
    "IoT energy monitoring",
    "net zero energy solutions",
    "BEE certified energy services",
    "smart energy management",
    "energy analytics platform",
    "ISO 50001 energy management",
    "building energy management system",
    "BEMS",
    "AI energy management",
    "energy performance contracting",
    "energy as a service",
    "industrial energy management",
    "commercial energy solutions",
    // 🇮🇳 INDIA
    "energy audit India",
    "energy audit services India",
    "energy management India",
    "energy services company India",
    "energy efficiency India",
    "net zero India",
    "BEE energy audit India",
    "energy audit Mumbai",
    "energy audit Delhi",
    "energy audit Bangalore",
    "energy audit Chennai",
    "energy audit Hyderabad",
    "energy audit Pune",
    "energy audit Ahmedabad",
    "industrial energy audit India",
    "energy services provider India",
    "smart energy solutions India",
    "energy consulting India",
    "energy cost reduction India",
    "carbon neutral India",
    // 🇸🇦 SAUDI ARABIA
    "energy audit Saudi Arabia",
    "energy audit KSA",
    "energy management Saudi Arabia",
    "energy services Saudi Arabia",
    "energy efficiency Saudi Arabia",
    "net zero Saudi Arabia",
    "Vision 2030 energy Saudi Arabia",
    "NEOM energy management",
    "industrial energy audit KSA",
    "energy consulting Saudi Arabia",
    "smart energy Saudi Arabia",
    "energy services Riyadh",
    "energy services Jeddah",
    "energy services NEOM",
    "carbon neutral Saudi Arabia",
    "green energy Saudi Arabia",
    // 🇸🇬 SINGAPORE
    "energy audit Singapore",
    "energy management Singapore",
    "energy services Singapore",
    "energy efficiency Singapore",
    "net zero Singapore",
    "Singapore Green Plan energy",
    "BCA energy audit Singapore",
    "industrial energy audit Singapore",
    "energy consulting Singapore",
    "smart energy Singapore",
    "energy services company Singapore",
    "carbon neutral Singapore",
    "green building energy Singapore",
    "energy management system Singapore",
    // 🇦🇪 UAE
    "energy audit UAE",
    "energy audit Dubai",
    "energy audit Abu Dhabi",
    "energy management UAE",
    "energy services UAE",
    "energy efficiency UAE",
    "net zero UAE",
    "UAE Net Zero 2050 energy",
    "industrial energy audit UAE",
    "energy consulting Dubai",
    "smart energy UAE",
    "carbon neutral UAE",
    "green energy Dubai",
    "energy services Abu Dhabi",
    "Masdar energy solutions UAE",
    // 🇶🇦 QATAR
    "energy audit Qatar",
    "energy audit Doha",
    "energy management Qatar",
    "energy services Qatar",
    "energy efficiency Qatar",
    "net zero Qatar",
    "Qatar National Vision energy",
    "industrial energy audit Qatar",
    "smart energy Qatar",
    "energy consulting Doha",
    "carbon neutral Qatar",
    // 🇧🇭 BAHRAIN
    "energy audit Bahrain",
    "energy management Bahrain",
    "energy services Bahrain",
    "energy efficiency Bahrain",
    "net zero Bahrain",
    "industrial energy audit Bahrain",
    "smart energy Bahrain",
    // 🇰🇼 KUWAIT
    "energy audit Kuwait",
    "energy management Kuwait",
    "energy services Kuwait",
    "energy efficiency Kuwait",
    "industrial energy audit Kuwait",
    "net zero Kuwait",
    // 🇴🇲 OMAN
    "energy audit Oman",
    "energy management Oman",
    "energy services Oman",
    "energy efficiency Oman",
    "net zero Oman",
    "Oman Vision 2040 energy",
    "industrial energy audit Oman",
    // 🇲🇾 MALAYSIA
    "energy audit Malaysia",
    "energy audit Kuala Lumpur",
    "energy management Malaysia",
    "energy services Malaysia",
    "energy efficiency Malaysia",
    "net zero Malaysia",
    "industrial energy audit Malaysia",
    "energy consulting Malaysia",
    "smart energy Malaysia",
    // 🇮🇩 INDONESIA
    "energy audit Indonesia",
    "energy audit Jakarta",
    "energy management Indonesia",
    "energy services Indonesia",
    "energy efficiency Indonesia",
    "net zero Indonesia",
    "industrial energy audit Indonesia",
    "energy consulting Indonesia",
    // 🇵🇭 PHILIPPINES
    "energy audit Philippines",
    "energy audit Manila",
    "energy management Philippines",
    "energy services Philippines",
    "energy efficiency Philippines",
    "net zero Philippines",
    "industrial energy audit Philippines",
    // 🇹🇭 THAILAND
    "energy audit Thailand",
    "energy audit Bangkok",
    "energy management Thailand",
    "energy services Thailand",
    "energy efficiency Thailand",
    "net zero Thailand",
    "industrial energy audit Thailand",
    // 🇻🇳 VIETNAM
    "energy audit Vietnam",
    "energy audit Ho Chi Minh",
    "energy management Vietnam",
    "energy services Vietnam",
    "energy efficiency Vietnam",
    "net zero Vietnam",
    // 🇬🇧 UK
    "energy audit UK",
    "energy audit London",
    "energy management UK",
    "energy services UK",
    "energy efficiency UK",
    "net zero UK",
    "ESOS energy audit UK",
    "industrial energy audit UK",
    "energy consulting UK",
    // 🇺🇸 USA
    "energy audit USA",
    "energy audit United States",
    "energy management USA",
    "energy services USA",
    "energy efficiency USA",
    "net zero USA",
    "industrial energy audit USA",
    "energy consulting USA",
    "ASHRAE energy audit USA",
    // 🇦🇺 AUSTRALIA
    "energy audit Australia",
    "energy audit Sydney",
    "energy audit Melbourne",
    "energy management Australia",
    "energy services Australia",
    "energy efficiency Australia",
    "net zero Australia",
    "industrial energy audit Australia",
    // 🇨🇦 CANADA
    "energy audit Canada",
    "energy audit Toronto",
    "energy management Canada",
    "energy services Canada",
    "energy efficiency Canada",
    "net zero Canada",
    "industrial energy audit Canada",
    // 🇩🇪 GERMANY
    "energy audit Germany",
    "energy management Germany",
    "energy services Germany",
    "energy efficiency Germany",
    "net zero Germany",
    "Energieaudit Germany",
    "industrial energy audit Germany",
    // 🇫🇷 FRANCE
    "energy audit France",
    "energy management France",
    "energy services France",
    "energy efficiency France",
    "net zero France",
    // 🇯🇵 JAPAN
    "energy audit Japan",
    "energy audit Tokyo",
    "energy management Japan",
    "energy services Japan",
    "energy efficiency Japan",
    "net zero Japan",
    "industrial energy audit Japan",
    // 🇰🇷 SOUTH KOREA
    "energy audit South Korea",
    "energy audit Seoul",
    "energy management South Korea",
    "energy services South Korea",
    "energy efficiency South Korea",
    "net zero South Korea",
    // 🌍 GLOBAL
    "global energy audit services",
    "international energy management",
    "worldwide energy services",
    "global net zero solutions",
    "multinational energy consulting",
    "global energy efficiency solutions",
    "international energy audit company",
    "cross border energy services",
    "global decarbonization solutions",
    "worldwide carbon neutral solutions",
  ],
  openGraph: {
    title: "Energy Solutions | Sustainabyte",
    description: "Comprehensive energy management and efficiency solutions",
    type: "website",
    url: "https://sustainabyte.ai/energy",
    images: [
      {
        url: "/opengraph-image.png",
        width: 1200,
        height: 630,
        alt: "Sustainabyte Energy",
      },
    ],
  },
  alternates: {
    canonical: "https://sustainabyte.ai/energy",
    languages: {
      "en-IN": "https://sustainabyte.ai/energy",
      "en-AE": "https://sustainabyte.ai/energy",
      "en-SA": "https://sustainabyte.ai/energy",
      "en-SG": "https://sustainabyte.ai/energy",
      "en-MY": "https://sustainabyte.ai/energy",
      "en-QA": "https://sustainabyte.ai/energy",
      "en-GB": "https://sustainabyte.ai/energy",
      "en-US": "https://sustainabyte.ai/energy",
      "en-AU": "https://sustainabyte.ai/energy",
      "en-CA": "https://sustainabyte.ai/energy",
    },
  },
};

export default function EnergyLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return children;
}
